apiVersion: v1
kind: ServiceAccount
metadata:
  name: dct-backend-sa
  namespace: dct
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dct-backend-role
  namespace: dct
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dct-backend-binding
  namespace: dct
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dct-backend-role
subjects:
  - kind: ServiceAccount
    name: dct-backend-sa
    namespace: dct