apiVersion: v1
kind: ServiceAccount
metadata:
  name: dct-backend-sa
  labels:
    app.kubernetes.io/name: dct-backend
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: dct-helm
    meta.helm.sh/release-namespace: dct
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dct-backend-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dct-backend-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dct-backend-role
subjects:
  - kind: ServiceAccount
    name: dct-backend-sa
