apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudops-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudops-frontend
  template:
    metadata:
      labels:
        app: cloudops-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-auth
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.servicePort }}
