apiVersion: apps/v1
kind: Deployment
metadata:
  name: dct-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dct-backend
  template:
    metadata:
      labels:
        app: dct-backend
    spec:
      imagePullSecrets:
        - name: dockerhub-auth
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.servicePort }}
          envFrom:
            - configMapRef:
                name: dct-config
            - secretRef:
                name: dct-secret