apiVersion: apps/v1
kind: Deployment
metadata:
  name: dct-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dct-frontend
  template:
    metadata:
      labels:
        app: dct-frontend
    spec:
      imagePullSecrets:
        - name: dockerhub-auth
      containers:
        - name: frontend
          image: {{ .Values.frontend.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.frontend.servicePort }}
          env:
            - name: REACT_APP_ENV
              value: "production"
            - name: NODE_ENV
              value: "production"
