{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudops-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /api/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cloudops-backend
                port:
                  number: {{ .Values.backend.servicePort }}
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: cloudops-frontend
                port:
                  number: {{ .Values.frontend.servicePort }}
{{- end }}