{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dct-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: {{ .Values.ingress.annotations.cert-manager.io/cluster-issuer }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          # ✅ Static files like /static/js/main.js
          - path: /static(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dct-frontend
                port:
                  number: {{ .Values.frontend.servicePort }}

          # ✅ API rewrite /api → backend with path stripping
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dct-backend
                port:
                  number: {{ .Values.backend.servicePort }}
            # Annotation used here: rewrite-target: /$2

          # ✅ Catch-all route for React (index.html)
          - path: /(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dct-frontend
                port:
                  number: {{ .Values.frontend.servicePort }}
{{- end }}
