apiVersion: v1
kind: Service
metadata:
  name: dct-backend
spec:
  type: ClusterIP
  selector:
    app: dct-backend
  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.servicePort }}