apiVersion: v1
kind: Service
metadata:
  name: dct-frontend
spec:
  type: ClusterIP
  selector:
    app: dct-frontend
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.servicePort }}
