apiVersion: v1
kind: Service
metadata:
  name: cloudops-frontend
spec:
  type: ClusterIP
  selector:
    app: cloudops-frontend
  ports:
    - port: {{ .Values.frontend.servicePort }}
      targetPort: {{ .Values.frontend.servicePort }}
