backend:
  image: mitechllc/cloudops-backend:latest
  servicePort: 4000
frontend:
  image: mitechllc/cloudops-frontend:latest
  servicePort: 80

ingress:
  enabled: true
  host: cloudops-center.kihhuf.org